#ifndef RETRIEVAL_POINTERS_AND_REFCOUNT_BUFFER_HPP
#define RETRIEVAL_POINTERS_AND_REFCOUNT_BUFFER_HPP

/**
 * @file retrieval_pointers_and_refcount_buffer.hpp
 * @brief RETRIEVAL_POINTERS_AND_REFCOUNT_BUFFER struct definition
 */



#endif // RETRIEVAL_POINTERS_AND_REFCOUNT_BUFFER_HPP
